### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by AlbertoRemus** [jkulhanek/viewformer#1]
Hello and thanks for sharing this great work!

I would like to ask some questions, since I'm interested in using this work to extract meshes of the object for unseen instances of a seen (during training) category

* First of all: is this method capable of retrieving the 3D model from a _single view_ within the same category? (Testing on instances not seen during the training)

* Is the extracted 3D model with the correct scale?

* Is there any method in this repo to generate and export mesh as .obj/.ply ?

Thanks in advance

**Comment by jkulhanek** [comment]
Hi,
Thank you for taking interest in our work. To answer your questions:
- Yes, the method will also be able to render a previously unseen scene from a single image, but it would be better to use more images.
- It does not extract a 3D model. It operates only in 2D image space.
- It is not possible to generate a mesh.

**Comment by AlbertoRemus** [comment]
Thanks for your prompt reply! 
Given I got the information I needed, I gonna close this issue then
