### ISSUE TITLE
PyTorch Version

### ISSUE THREAD

**Issue by haoranD** [jkulhanek/viewformer#5]
Hi,

Many thanks for your excellent work.

I am truly interested in your work and currently trying to play the code.

May I ask if is there any PyTorch version code for training and testing?

Thanks a lot.

**Comment by jkulhanek** [comment]
Hi,

Thank you for your interest. The codebook is implemented in both TF and PyTorch, but unfortunately, there is not PyTorch code for the transformer.

**Comment by haoranD** [comment]
Sure, thank you for your kind reply. Have a nice one.
