### ISSUE TITLE
Site hosting checkpoints is down

### ISSUE THREAD

**Issue by rachelzh9** [jkulhanek/viewformer#7]
I am unable to ping `https://data.ciirc.cvut.cz/public/projects/2022ViewFormer/checkpoints`

**Comment by jkulhanek** [comment]
I know about the issue. I am very sorry. There was an unexpected event at our university cluster and it will be offline till Tuesday. Again, I am sorry about the caused trouble.

**Comment by jkulhanek** [comment]
Should be now resolved.
