### ISSUE TITLE
Dataloader generation not unzipping all files

### ISSUE THREAD

**Issue by rachelzh9** [jkulhanek/viewformer#8]
Like mentioned in this [issue](https://github.com/jkulhanek/viewformer/issues/6#issuecomment-1495409463) , I tried putting several downloaded InteriorNet zip files in the HD7 folder and ran the dataset generation command 
```
viewformer-cli dataset generate --loader interiornet --path /home/ec2-user/novel-cross-view-generation/viewformer/data --image-size 128 --output /home/ec2-user/novel-cross-view-generation/viewformer/dataset/interiornet --max-sequences-per-shard 50 --shuffle --split test
```
However, I am interested in using > 20 context images, but currently the dataset generation only unzips 20 images per sequence. How can I set it to unzip more of them?

**Comment by rachelzh9** [comment]
Ok I see, HD7 only has 20 images per zip file. If I want to use custom inputs, i.e. my own images from a video, what would be the best way to go about that?

**Comment by jkulhanek** [comment]
I wanted to add the custom loader, but didn't have enough time recently. If you have  a video, did you use a SfM to get the camera poses? COLMAP?
I was thinking about which format would be preferable for most user. Do you want to load the COLMAP sparse model? Or do you want to specify the poses with a json?
I don't know when I get to it. But if you want to write your own loader, it should be quite easy if you start from the 7Scenes loader.

Closing this issue now and creating a new one to track using custom data with viewformer.
